services:
  jupyter-notebook-service:
    container_name: jupyter-notebook-container
    build: .
    platform: linux/amd64
    ports:
      - "8888:8888"
    env_file: .env
    stdin_open: true
    tty: true
    volumes:
      - .:/app

# services:
#   spark:
#     build: .
#     environment:
#       - SPARK_MODE=master
#       - SPARK_RPC_AUTHENTICATION_ENABLED=no
#       - SPARK_RPC_ENCRYPTION_ENABLED=no
#       - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
#       - SPARK_SSL_ENABLED=no
#       - SPARK_USER=spark
#     ports:
#       - '8080:8080'
#       - '7077:7077'

#   spark-worker:
#     build: .
#     environment:
#       - SPARK_MODE=worker
#       - SPARK_MASTER_URL=spark://spark:7077
#       - SPARK_WORKER_MEMORY=1G      #<--- adjust accordingly
#       - SPARK_WORKER_CORES=1
#       - SPARK_RPC_AUTHENTICATION_ENABLED=no
#       - SPARK_RPC_ENCRYPTION_ENABLED=no
#       - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
#       - SPARK_SSL_ENABLED=no
#       - SPARK_USER=spark